plugins {
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.micronaut.application") version "4.4.4"
    id("io.micronaut.aot") version "4.4.4"
}

version = "0.1"
group = "com.frogdevelopment"

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor(mn.micronaut.http.validation)
    annotationProcessor(mn.micronaut.serde.processor)
    annotationProcessor(mn.micronaut.data.processor)
    annotationProcessor(mn.micronaut.openapi)

    implementation(mn.micronaut.context.propagation)
    implementation(mn.micronaut.reactor)
    implementation(mn.micronaut.serde.jackson)
    implementation(mn.micronaut.data.jdbc)
    implementation(mn.micronaut.jdbc.hikari)
    implementation(mn.micronaut.flyway)
    implementation(mn.micronaut.pulsar)

    compileOnly(mn.micronaut.http.client)
    compileOnly(mn.jakarta.persistence.api)
    compileOnly(mn.micronaut.openapi.annotations)

    runtimeOnly(mn.logback.classic)
    runtimeOnly(mn.snakeyaml)
    runtimeOnly(mn.mysql.connector.j)
    runtimeOnly(mn.h2)

    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.mockito.core)
    testImplementation(mn.assertj.core)
}


application {
    mainClass = "com.frogdevelopment.Application"
}
java {
    sourceCompatibility = JavaVersion.toVersion("21")
    targetCompatibility = JavaVersion.toVersion("21")
}


graalvmNative.toolchainDetection = false

micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("com.frogdevelopment.*")
    }
    aot {
        // Please review carefully the optimizations enabled below
        // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
        replaceLogbackXml = true
    }
}


tasks.named("dockerfileNative") {
    jdkVersion = "21"
}


