services:

  mariadb:
    hostname: mariadb
    image: bitnami/mariadb:10.5.12
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
