micronaut:
  application:
    name: issues-examples

datasources:
  default:
    url: jdbc:mariadb://localhost:3306/examples
    username: 'root'
    password: 'example'
    driver-class-name: 'org.mariadb.jdbc.Driver'
    dialect: MYSQL
#    schema-generate: create

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: true
      create-schemas: true
#      schemas: examples
#      default-schema: examples
